GET http://localhost:3001/api/users


###
GET http://localhost:3001/api/login


###
GET http://localhost:3001/api/blogs



//Main user for making posts
####
POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlaW4iLCJpZCI6IjYzNTljZGMwY2VhOWE4NDM0ZjE4ZmE0MSIsImRhdGVNYWRlIjoiMTAvMjYvMjAyMiwgODoxNjozMCBQTSIsImlhdCI6MTY2NjgyOTc5MH0.-0sl0CErtq4PPFuhycG6Y821Zr8ZsCi9oZPG0HEt550

{
    "url": "blog 2",
    "title": "My 3rd blog",
    "author": "kein",
    "likes": 2,
    "user_id": "6359cdc0cea9a8434f18fa41"
}

//Test user for making posts
####
POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYzNTljZTkxMTEwZjZhYmI4YjYyM2Y0NCIsImRhdGVNYWRlIjoiMTAvMjYvMjAyMiwgODoyMToyNiBQTSIsImlhdCI6MTY2NjgzMDA4Nn0.zlF_3MHbhmE262G3iFWdYEVlZU8nii6GoQyP_chAbMI

{
    "url": "blog 1 test",
    "title": "My 2nd blog",
    "author": "test",
    "likes": 123,
    "user_id": "6359ce91110f6abb8b623f44"
}

//Creating a new user
####
POST http://localhost:3001/api/users
content-type: application/json

{
    "username" : "test",
    "name": "test",
    "password": "test"
}


####
POST http://localhost:3001/api/users
content-type: application/json

{
    "username" : "kein",
    "name": "kein_name",
    "password": "kein"
}

###

//Login for primary user 
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "kein",
    "password": "kein"
}

###
//Login for test user
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "test",
    "password": "test"
}


###
 
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "keindummy",
    "password": "keindummy"
}

###
DELETE http://localhost:3001/api/blogs/6354785ba7f90f8973987b79
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlaW4iLCJpZCI6IjYzNGY1NDgzODQ0ZTI3NDVhMTU3NjJlMSIsImRhdGVNYWRlIjoiMTAvMjYvMjAyMiwgNzo1NTo0NCBQTSIsImlhdCI6MTY2NjgyODU0NH0.-hkpTcMmxcVze7h7yGcnZhufepJ1FdjOwmybltibEQw

###
DELETE http://localhost:3001/api/blogs/6354785ba7f90f8973987b79
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlaW4iLCJpZCI6IjYzNGY1NDgzODQ0ZTI3NDVhMTU3NjJlMSIsImRhdGVNYWRlIjoiMTAvMjYvMjAyMiwgNzo1NTo0NCBQTSIsImlhdCI6MTY2NjgyODU0NH0.-hkpTcMmxcVze7h7yGcnZhufepJ1FdjOwmybltibEQw
