rest-client.previewResponseInUntitledDocument = true

GET http://localhost:3001/api/persons

###
GET https://phonebook3.fly.dev/api/persons

###

DELETE http://localhost:3001/api/persons/"Kendrick Lamar"

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

//This is the "body" of the content we will send
{   
    "name": "Sir James",
    "number": 123454566
}

###
POST https://phonebook3.fly.dev/api/persons
content-type: application/json
//This is the "body" of the content we will send 

{   
    "id": 0,
    "name": "Snake",
    "number": 123454566
}

###

DELETE https://phonebook3.fly.dev/api/persons/2